# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  # using tox
  py27:
      docker:
        - image: python:2
      steps:
        - checkout
        - run: pip install pytest && pip install -r requirements.txt && python setup.py install
        - run: pytest
  py35:
      docker:
        - image: python:3.5
      steps:
        - checkout
        - run: pip install pytest && pip install -r requirements.txt && python setup.py install
        - run: pytest
  py36:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - run: pip install pytest && pip install -r requirements.txt && python setup.py install
        - run: pytest
  py37:
      docker:
        - image: python:3.7
      steps:
        - checkout
        - run: pip install pytest && pip install -r requirements.txt && python setup.py install
        - run: pytest
workflows:
  version: 2

  myproj:
    jobs:
      - py27
      - py35
      - py36
      - py37